const declarations = [
  "It is not the year 2020",
  "I want to inform you that it is not 2020",
  "Still checking...",
  "Nope, not 2020",
  "Definitely not 2020",
  "2020? naaah",
  "It's 2020! Ooops, no sorry!",
  "!2020",
  "No, no no no no no no no no Batman!",
  "No!",
  "No! No! No! No! NO! Mamma mia let me go",
  "This question again. You all want the same thing from me",
  "Ah! You scared me there for a second. But no, it is not the year 2020",
  "It seems that 2020 is in the past",
  "2020, just a memory",
  "It is gone baby!",
  "2020 is no more",
  "2020 is gone with the wind",
  "R.I.P. 2020",
  "I can assume it is not 2020",
  "I am merely a website but one thing is for sure, we are not in the year 2020",
  "What if it was 2020? It is just a number, what does it mean? Isn't time relative?",
  "My calculations say that it is not the year 2020",
  "Hey friend! You came here because you needed answers. Well, you came to the right place. IT IS NOT THE YEAR 2020",
  "From what I know it is not the year 2020",
  "Bee boop baa beap not!",
  "The answer is in your heart. And it is not 2020",
  "Felicitations! It is not the year 2020!",
  "My goodness! No!",
  "Hell no!",
  "Please don't ask again"
];

export default declarations;
